name: panda_map
description: Custom google map package
version: 0.0.1
homepage: https://github.com/dttrung-99931
# publish_to: none

environment:
  sdk: ">=2.19.6 <3.0.0" # <3.0.0 is interpreted as <4.0.0 for backward compatibility with old libs
  flutter: ">=1.17.0" # version 3.10.5 (dart 3)

dependencies:
  flutter:
    sdk: flutter
  location: ^6.0.2
   
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - packages/panda_map/assets/current_position.svg
